name: "page2"
title: "Vanessa di Lego"
description: |
  Workshop
output_dir: "."
navbar:
  right:
    - text: "Presentation"
      href: Presentation.html
    - text: "Codes"
      href: Codes.html
output: distill_article
creative_commons: CC BY
theme: jekyll-theme-cayman
