name: "page2"
title: "Vanessa di Lego"
description: |
  My Website
output_dir: "."
navbar:
  right:
    - text: "Presentation"
      href: Presentation.html
    - text: "Codes"
      href: Codes.html
output:
  distill::distill_article:
    includes:
      in_header: utterances.html
creative_commons: CC BY
theme: jekyll-theme-cayman
